# Generated by Django 4.1.7 on 2023-04-20 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=10, null=True, unique=True, verbose_name='Гос номер')),
                ('brand', models.CharField(max_length=200, verbose_name='Марка')),
                ('model', models.CharField(max_length=200, verbose_name='Модель')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год выпуска')),
                ('color', models.CharField(max_length=100, verbose_name='Цвет')),
                ('rudder_location', models.CharField(max_length=100, verbose_name='Расположение руля')),
                ('engine_volume', models.PositiveSmallIntegerField(verbose_name='Объем двигателя')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
        migrations.CreateModel(
            name='CarPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200, verbose_name='Марка')),
                ('model', models.CharField(max_length=200, verbose_name='Модель')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год выпуска')),
                ('color', models.CharField(max_length=100, verbose_name='Цвет')),
                ('rudder_location', models.CharField(max_length=100, verbose_name='Расположение руля')),
                ('engine_volume', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Объем двигателя')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена')),
                ('mileage', models.PositiveIntegerField(blank=True, null=True, verbose_name='Пробег')),
                ('transmission', models.CharField(blank=True, max_length=100, null=True, verbose_name='Коробка передач')),
                ('region', models.CharField(blank=True, max_length=255, null=True, verbose_name='Регион')),
                ('accounting', models.CharField(blank=True, max_length=200, null=True, verbose_name='Учёт')),
                ('another', models.CharField(max_length=500, verbose_name='Прочее')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_posts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.CreateModel(
            name='SpecialMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Отметка')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars_special_marks', to='cars.car')),
            ],
            options={
                'verbose_name': 'Особая отметка',
                'verbose_name_plural': 'Особые отметки',
            },
        ),
        migrations.CreateModel(
            name='PeriodsOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(auto_now_add=True, verbose_name='От')),
                ('before_date', models.DateField(blank=True, null=True, verbose_name='До')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars_periods_ownership', to='cars.car')),
            ],
            options={
                'verbose_name': 'Период владения',
                'verbose_name_plural': 'Периоды владения',
            },
        ),
        migrations.CreateModel(
            name='CarPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post_images/', verbose_name='Фотография поста')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_images', to='cars.carpost', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Фотография поста',
                'verbose_name_plural': 'Фотографии постов',
            },
        ),
        migrations.CreateModel(
            name='CarPostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Текст')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_comment', to='cars.carpost', verbose_name='Пост')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_comments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='CarPostFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_favorite', to='cars.carpost', verbose_name='Пост')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_favorite_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранные',
                'unique_together': {('user', 'post')},
            },
        ),
    ]
