# Generated by Django 4.1.7 on 2023-04-06 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_remove_periodsownership_actual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialmarks',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car'),
        ),
    ]
