# Generated by Django 4.1.7 on 2023-04-06 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_specialmarks_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialmarks',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars_special_marks', to='cars.car'),
        ),
    ]
