# Generated by Django 4.1.7 on 2023-04-20 10:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0009_carpostimage_carpostfavorite_carpostcomment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carpostfavorite',
            unique_together={('user', 'post')},
        ),
    ]
